# ===== docker-compose.yml =====
services:
    db:
        image: postgres:17-alpine
        env_file: .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
            interval: 5s
            timeout: 3s
            retries: 10
        restart: unless-stopped

    migrator:
        build: ./apps/api
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./apps/api/prisma:/app/prisma
        command: ['sh', '-c', './scripts/migrate.sh']
        restart: 'no'

    api:
        build: ./apps/api
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully
        ports:
            - '8080:8080'
        volumes:
            - uploads_data:/app/uploads
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'wget', '-qO-', 'http://localhost:8080/health']
            interval: 30s
            timeout: 5s
            retries: 3

    web:
        build: ./apps/web
        env_file: .env
        environment:
            VITE_API_URL: http://localhost:8080
        depends_on:
            api:
                condition: service_started
        ports:
            - '5173:5173'
        volumes:
            - ./apps/web:/app
            - web_node_modules:/app/node_modules
        restart: unless-stopped

volumes:
    db_data:
    uploads_data:
    web_node_modules:
